apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fkbhp6fyb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fkbhp6fyb-go 
  name: fkbhp6fyb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fkbhp6fyb-go 
